server.port=9090
spring.datasource.url=jdbc:postgresql://localhost:5432/cnc_monitordb
spring.datasource.username=postgres
spring.datasource.password=didimari

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false